### ISSUE TITLE
Consensus lock out at 3+ nodes after constant transaction streaming

### ISSUE THREAD

**Issue by andrecronje** [Fantom-foundation/go-lachesis#115]
**Describe the bug**
Boot 3 nodes.
Attach a VM
Send transactions consistently (1/sec) to VM
After few minutes consensus will stop occurring

**To Reproduce**
1. Boot 3 nodes.
2. Attach a VM
3. Send transactions consistently (1/sec) to VM
4. After few minutes consensus will stop occurring

**Expected behavior**
Continue to reach consensus

**Comment by devintegral** [comment]
outdated
