### ISSUE TITLE
Add timestamp to block

### ISSUE THREAD

**Issue by andrecronje** [Fantom-foundation/go-lachesis#125]
**Describe the solution you'd like**
Add timestamp to block is created.

**Comment by Maxime2** [comment]
Without time synchronisation functionality this makes no sense.
More, it is not required by Lachesis according to paper, - it uses Lamport timestamps which we already have.

**Comment by Maxime2** [comment]
Without time synchronisation these timestamp based stats will be vague for blocks created outside current node, especially on small time intervals (with length comparable to possible time gap between nodes).
Should we implement time synchronisation as another kind of internal transaction or leave it as a requirement for nodes generating new blocks is a question.

**Comment by andrecronje** [comment]
Only a requirement for the explorer, so it can be dependent on the local node, no current requirement to add complexity.
