### ISSUE TITLE
Error handling: every func returning (err error)?

### ISSUE THREAD

**Issue by SamuelMarks** [Fantom-foundation/go-lachesis#141]
Related: https://github.com/Fantom-foundation/go-lachesis/pull/140

As for whether to return one or [mutliple](https://pocketgophers.com/handling-errors-in-defer/#returning-multiple-errors), that's a worthy debate. https://github.com/hashicorp/go-multierror is another option.

Would be good to remove all `panic`s and `Fatal` calls, outside of the topmost entrypoint (i.e.: `main` and tests).

**Comment by devintegral** [comment]
outdated
