### ISSUE TITLE
RLP and protobuf comparison

### ISSUE THREAD

**Issue by Maxime2** [Fantom-foundation/go-lachesis#158]
Some code from go-ethereum project were introduced into the project (see #136 and #157 ). Ethereum uses RLP for data serialisation throughout its stack, https://github.com/ethereum/wiki/wiki/Design-Rationale#rlp , however we use protobuf in lachesis, which is more universal solution and up to this point haven't caused any issue with serialisation.

From design perspective we better use only one serialisation library, however if RLP is significantly faster that protobuf, it would make sense to use RLP for storing data on the node. Though that approach would make the database not transferable to other platforms (such transfer would be costly and would require additional tools to convert data, to be honest)

As RLP is binary-oriented serialisator it is not suitable for communications over the network, we need to keep protobuf to communicate over the net.

To do selection consciously, we need to compare RPL and protobuf from performance perspective - which one is faster and how much, and weighs out other reasons for using or not of RPL / protobuf.

**Comment by devintegral** [comment]
@Maxime2, is comparison correct?

**Comment by Maxime2** [comment]
Put rand.Seed(1) at the beginning of both BenchmarkRlp() and BenchmarkProto() - you will have the same random sequence for both.

Then change randRlpEvent() to this:
```
func randRlpEvent() *posposet.Event {
	creator := common.FakeAddress()

	return &posposet.Event{
		Index:                rand.Uint64(),
		Creator:              creator,
		ExternalTransactions: randTxns(),
		Parents:              posposet.FakeEventHashes(2),
	}
}
```
so randRlpEvent() and randProtoEvent() would call the same sequence of random things to generate.

Also it's better go generate N-element array of events in both  BenchmarkRlp() and BenchmarkProto() before resetting timer and test different events of each iteration of the cycle, - that would be closer to real-life serialisation/deserialisation.

**Comment by devintegral** [comment]
Conclusion: ProtoBuf serialization is more then 2 times faster then RLP.

**Comment by Olshansk** [comment]
Came by this thread while doing some research so just wanted to add some points for future readers.

The Ethereum Org has 2 primary reasons for using RLP ([source](https://eth.wiki/en/fundamentals/design-rationale)):
```
1. Simplicity of implementation
2. Guaranteed absolute byte-perfect consistency
```

Aside from the benchmarking done here, in my personal opinion, I also believe the following:
1. There are enough open-source implementations of common codecs that a new project does not need to implement its own.
2. RLP does not provide a benefit on compression, network latency or serialization/deserialization time.
3. If the order of keys & values (e.g. protobuf maps) is important, they could be committed and replaced with a proto wrapper containing keys & values.
