### ISSUE TITLE
Task: support a variation of event creation rates on nodes

### ISSUE THREAD

**Issue by quan8** [Fantom-foundation/go-lachesis#168]
**Is your feature request related to a problem? Please describe.**
Need to simulate different event creation rates on different nodes.

We want to simulate scenarios like below:
1) 1 of 5 nodes have a creation rate of 20% compared to other nodes
2) 2/3 of nodes have a low creation rate (5%)
3) some nodes can't create new events

**Describe the solution you'd like**
Add a parameter to control the event creation rate on nodes.
Can add a flag on node config

**Comment by devintegral** [comment]
outdated
