### ISSUE TITLE
peers.json is not created

### ISSUE THREAD

**Issue by quan8** [Fantom-foundation/go-lachesis#172]
**Describe the bug**
The creation of peers.json is not robust. The file is not generated.

**To Reproduce**
1. compile the code 
2. run the simulation
3. Got error

[
  {
    "NetAddr": "127.0.0.1:12002",
    "PubKeyHex": "0x0481CDABD15A88A5EAF36A1B78FC203F3284232B793C2B0E6B8B20AD04975682FDB39183510C604EAF86CBFB9A67F4F766DCC23DFC91ACE36954598927D5F636A2"
  },
  {
    "NetAddr": "127.0.0.1:12003",
    "PubKeyHex": "0x04F02664BF95DA2C79BC4E634D18066E8552D39F26D3CC0111F045BFD802D5BBF655DCBE447DF5ECE63A5C2F1B3753E463DEBFE4A818539903723A7014D0C6299D"
  },
  {
    "NetAddr": "127.0.0.1:12004",
    "PubKeyHex": "0x04F08C3C9E25FD7FD65588C952A4CD721CE947B35F8DD11F4579FC64C62CAD8B056874589855DD93662DF7E906F705425F1024A9E3AFA9281AD82246D0A4A33F5B"
  }
]
cat: /home/qn/work/src/github.com/Fantom-foundation/go-lachesis/nodes/peers.json: No such file or directory

**Comment by Maxime2** [comment]
Hi Quan,
What branch of go-lachesis do you try to run?
Please provide the full output starting from the command line you use to run the simulation and all messages are produced afterwards.

**Comment by Maxime2** [comment]
Got message from Quan:

> Hi Maxim
> ￼￼￼￼￼
> 12:20 PM
> you can check out, make install
> 12:20 PM
> maybe glide update
> 12:20 PM
> then run
> 12:20 PM
> I got an error: the peers.json file is not generated.
> 12:21 PM
> you can double-check
> 12:21 PM
> master branch
> 12:21 PM
> Just double-check if you see the same error.
> new messages
> 12:22 PM
> if can't reproduce, you can close it.

The correct command to rebuild everything is:
`make clean vendor proto build`

After that successfully completes on the latest master you can run simulation using this command:
`n=25 entry=main logshold=-1,-1,-1,85,0,0 BUILD_DIR="$PWD" ./scripts/multi.bash`

Just have checked it with the latest master as of today and it works without any issue.

@quan8 Please try on your system the steps above and report if you still have an issue or the problem is resolved.

**Comment by Maxime2** [comment]
@quan8 Please also check that you have the latest batch-ethkey installed:
`go get -v github.com/SamuelMarks/batch-ethkey`

**Comment by quan8** [comment]
Steps:
Make a fresh clone: 
$git clone xxx
$make clean vendor proto build
$n=3 entry=main logshold=-1,-1,-1,85,0,0 BUILD_DIR="$PWD" ./scripts/multi.bash
----

Output and Error:
<========== start of output =====
$ n=3 entry=main logshold=-1,-1,-1,85,0,0 BUILD_DIR="$PWD" bash -x ./scripts/multi.bash
+ set -euo pipefail
+ declare -i OPTIND=1
+ declare -i debug=0
+ declare args=
+++ dirname ./scripts/multi.bash
++ cd ./scripts
++ pwd
+ declare -r DIR=/home/qn/work/src/github.com/Fantom-foundation/go-lachesis/scripts
+ getopts d opt
+ shift 0
+ '[' '' = -- ']'
+ '[' 0 == 1 ']'
+ /home/qn/work/src/github.com/Fantom-foundation/go-lachesis/scripts/multi_build.bash ''
# of logical CPUs:  4
# of physical CPUS: 2
# command-line-arguments
/tmp/go-link-318665185/000002.o: In function `mygetgrouplist':
/workdir/go/src/os/user/getgrouplist_unix.go:16: warning: Using 'getgrouplist' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-318665185/000001.o: In function `mygetgrgid_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:38: warning: Using 'getgrgid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-318665185/000001.o: In function `mygetgrnam_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:43: warning: Using 'getgrnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-318665185/000001.o: In function `mygetpwnam_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:33: warning: Using 'getpwnam_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
/tmp/go-link-318665185/000001.o: In function `mygetpwuid_r':
/workdir/go/src/os/user/cgo_lookup_unix.go:28: warning: Using 'getpwuid_r' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
[
  {
    "NetAddr": "127.0.0.1:12002",
    "PubKeyHex": "0x044A869F291D672268D52F0F00A71D1DF6EBA757B2FB12D1C71E48A9E48E2951EB87374D3340FA14ED0CC5712E64AA358C80F43B2FBE9964EDF45E27B01697A513"
  },
  {
    "NetAddr": "127.0.0.1:12003",
    "PubKeyHex": "0x04EFC9C9288F7043684BEE8257F7879ABA5CFCE03C2DC3C966467AD64208B1D0FD7384D63AD398F8771CA2DCFF4613CF928422777ED9184CEE946B97E5BA67B1E7"
  },
  {
    "NetAddr": "127.0.0.1:12004",
    "PubKeyHex": "0x04EBE320F92C429E78B4964209F4B2B7C4B8B49C83AD97ECFCA311F064B288B35860CAAB91E0CBFF2EAF28A04754ECFB629E0C5F9BFEB9EA29D7366B89DA2FA7AD"
  }
]
cat: /home/qn/work/src/github.com/Fantom-foundation/go-lachesis/nodes/peers.json: No such file or directory
======= end of output ====>

**Comment by Maxime2** [comment]
Obviously it should be
`go get -u github.com/SamuelMarks/batch-ethkey`
to get updated version of batch-ethkey

**Comment by quan8** [comment]
It is version issue. Fixed with update: go get -u -v github.com/SamuelMarks/batch-ethkey

It'd be good to make it part of the build process (whenever something is updated). You can close it if you think it's not.

**Comment by Maxime2** [comment]
batch-ethkey is an external tool mentioned in requirements. You had an old version of it.

Versioning is already proposed, see #53

**Comment by quan8** [comment]
Thanks.
