### ISSUE TITLE
A schema of Byzantine attack on go-lachesis

### ISSUE THREAD

**Issue by Maxime2** [Fantom-foundation/go-lachesis#253]
**Describe the bug**
Lachesis is prone to a Byzantine attack of the following schema.

**To Reproduce**
1. A byzantine node receive a penultimate root event (an event having exactly 2*n/3 other roots in its flag table);
2. Byzantine node creates two events with different payload and referencing that penultimate root event as other parent for these events;
3. Then the byzantine nodes sends one of these events to half of other nodes as its next event; and sends the second event as its next to other half of other nodes;
4. Both of these byzantine events will be considering root by any node receiving them according to Section 3.10 of [1], as it will have 2*n/3 + 1 roots in their flag table, effectively creating a fork in the network.

**Expected behaviour**
Lachesis should prevent such an attack.

**Additional context**
Apparently, using only flag table for fast root selection is not enough to prevent such a byzantine fault and this aspect of Lachesis must be redesigned.

[1]. Sang-Min Choi, Jiho Park, Quan Nguyen, and Andre Cronje, FANTOM: A SCALABLE FRAMEWORK FOR ASYNCHRONOUS DISTRIBUTED SYSTEMS; https://arxiv.org/abs/1810.10360

**Comment by quan8** [comment]
There is a proof that there exists an honest node that will detect the fork and will notify the rest of the network. We have introduced a new PoS model, which is even more secure. Please discuss this kind of questions among the team first before raising issue..
