### ISSUE TITLE
hashicorp golang-lru breaks in Go 1.12 when using byte / uint8 array as a key

### ISSUE THREAD

**Issue by dev10** [Fantom-foundation/go-lachesis#273]
**Describe the bug**
Using a byte array as a key from Go version 1.12 is broken for the golang-lru.
When trying to run the Docker script in the posposet2 branch (go-lachesis/src/poslachesis/docker/Dockerfile), it panics. 
It also panics when trying to run 

> lachesis start --db=/tmp

It works fine if you change the Dockerfile to use:
> FROM golang:1.11 as build

**To Reproduce**

```
c, _ := lru.New(1)
key := []byte{1}
c.Add(key, 1) // Panic 
```
or
```
c, _ := lru.New(1)
key := []byte{1}
c.Get(key) // Panic
```

**Expected behavior**
It should store or retrieve a value from the cache

**Desktop (please complete the following information):**
 - OS: Linux
 - Golang: 1.12.7

**Additional context**
Similar problem was found here: https://github.com/projectcalico/felix/issues/1965

**Comment by Maxime2** [comment]
You're passing a slice as a key, not an array, try the following:
```
key := [...]byte{1}
```
Slices can not be used as keys for a map, see https://golang.org/ref/spec#Map_types

**Comment by dev10** [comment]
> You're passing a slice as a key, not an array, try the following:
> 
> ```
> key := [...]byte{1}
> ```
> 
> Slices can not be used as keys for a map, see https://golang.org/ref/spec#Map_types

Thanks Maxime2 that might explain why this code is causing a panic:
https://github.com/Fantom-foundation/go-lachesis/blame/e04ba9632444f31b119e90a40fec940539c6b847/src/posposet/store_frame.go#L26:L38

```
// GetFrame returns stored frame.
func (s *Store) GetFrame(n idx.Frame, sf idx.SuperFrame) *Frame {
	key := []byte(fmt.Sprintf("%d_%d", sf, n))

	if s.cache.Frames != nil {
		if f, ok := s.cache.Frames.Get(key); ok {
			w := f.(*wire.Frame)
			return WireToFrame(w)
		}
	}

	w, _ := s.get(s.table.Frames, key, &wire.Frame{}).(*wire.Frame)
	return WireToFrame(w)
}
```
