### ISSUE TITLE
EVM and Lachesis connection terminates if one node disconnects

### ISSUE THREAD

**Issue by andrecronje** [Fantom-foundation/go-lachesis#28]
**Describe the bug**
Once connectivity has been established between an EVM node and Lachesis node if one disconnects the channel is shut down and not restarted. This is not the problem with older versions of the EVM and only introduced in the new version

**To Reproduce**
1. Start Lachesis node
2. Start EVM node
3. Disconnect Lachesis node
4. (Optional) Reconnect Lachesis node
5. Attempt to send transaction from EVM to lachesis

**Expected behavior**
The EVM (or Lachesis) node should reconnect as soon as a new channel is created

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Lachesis Version 0.3.0

**Comment by devintegral** [comment]
outdated
