### ISSUE TITLE
Task: formatting error messages, define error codes

### ISSUE THREAD

**Issue by quan8** [Fantom-foundation/go-lachesis#314]
**Is your feature request related to a problem? Please describe.**
There are many types of errors in the system. Tracking by error messages is not easy. 
For example, "Message too long", if seen in the log, does not give a direct context of the error.

**Describe the solution you'd like**
For better tracking and debugging, suggest to define error codes that are accompanied with error strings.

For example, in protocol.go, 
- const ErrMsgTooLarge = 0
- ErrMsgTooLarge:             "Message too long"

- Need something like: CodeMsgTooLarge: "PRO_1001"
So logs should contain something like "PRO_1001: Message too long".

**Comment by devintegral** [comment]
outdated
