### ISSUE TITLE
Implement a light-client

### ISSUE THREAD

**Issue by andrecronje** [Fantom-foundation/go-lachesis#34]
**Describe the solution you'd like**
Nodes that do not form part of consensus, but simply receive events.

**Comment by AgustinCB** [comment]
Can you provide a deeper specification, please?

Once I have more details on what's needed, I'd be happy to implement this.

**Comment by SamuelMarks** [comment]
I'm guessing that what @andrecronje has in mind, is to use qRPC to generate a light CLI client.

Please confirm

**Comment by devintegral** [comment]
outdated
