### ISSUE TITLE
./stop.sh: line 16: blockade: command not found

### ISSUE THREAD

**Issue by MKong** [Fantom-foundation/go-lachesis#353]
**Describe the bug**
When running `./stop.sh` to stop the running nodes that are created by executing `./start.sh`, the following error appears (although the nodes appear to successfully stop running):

`./stop.sh: line 16: blockade: command not found`

**To Reproduce**
1. Go to 'https://github.com/Fantom-foundation/go-lachesis/tree/scope2#running-the-demo`
2. `cd docker/`
3. Run `make`
3. Run `./start`
4. Run `./stop.sh`

Error will appear.

**Expected behavior**
No error should be thrown

**Desktop**
 - OS: Mac OSX Mojave version 10.14.6

**Comment by devintegral3** [comment]
Please try to use Lachesis from the latest scope2 branch. This issue is fixed by #356

**Comment by quan8** [comment]
It's fixed.
