### ISSUE TITLE
test_cmd.go test failure

### ISSUE THREAD

**Issue by quan8** [Fantom-foundation/go-lachesis#357]
**Describe the bug**
est_cmd.go test failed

**To Reproduce**
$go test ./...

--- FAIL: **TestWalletImport** (5.06s)
    test_cmd.go:250: (stderr) INFO [10-18|14:42:40.025] Maximum peer count                       ETH=50 LES=0 total=50
    test_cmd.go:250: (stderr) INFO [10-18|14:42:40.025] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
    test_cmd.go:231: killing the child process (timeout)
    test_cmd.go:112: Not enough output, got until ◊:
        ---------------- (stdout text)
        !! Unsupported terminal, password will be echoed.
        Passphrase: 
        
        ---------------- (expected text)
        !! Unsupported terminal, password will be echoed.
        Passphrase: 
        ◊Address: {d4584b5f6229b7be90727b0fc8c6b91bb427821f}

--- FAIL: TestFakeNetFlag (6.05s)
    test_cmd.go:250: (stderr) INFO [10-18|14:42:56.917] Maximum peer count                       ETH=0 LES=0 total=0
    test_cmd.go:250: (stderr) INFO [10-18|14:42:56.917] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
    test_cmd.go:231: killing the child process (timeout)
    test_cmd.go:112: Not enough output, got until ◊:
        ---------------- (stdout text)
        
        ---------------- (expected text)
        ◊Welcome to the Geth JavaScript console!
        
        instance: go-lachesis/v1.9.1-stable/linux-amd64/go1.12.1
        coinbase: 0xf88d5892faf084dcf4143566d9c9b3f047c153ca
        at block: 0 (Mon, 05 Aug 2019 20:13:20 AEST)
         datadir: /tmp/lachesis-test681905840
         modules: admin:1.0 debug:1.0 eth:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

**Expected behavior**
No failed test

**Comment by devintegral3** [comment]
The most of console-related tests aren't deterministic, and rarely fail on slow or loaded servers. We'll look into them in more detail.

**Comment by devintegral** [comment]
outdated
