### ISSUE TITLE
Integration test with 150 nodes fails to produce a block in 20 minutes

### ISSUE THREAD

**Issue by Maxime2** [Fantom-foundation/go-lachesis#378]
**Describe the bug**
Integration test run with 150 nodes fails to produce a block in 20 minutes

**To Reproduce**
1. checkout the `master` branch
2. apply the following patch to increase the number of nodes and test running time:
```
diff --git a/integration/integration_test.go b/integration/integration_test.go
index 7d92e2a4..620ae3c0 100644
--- a/integration/integration_test.go
+++ b/integration/integration_test.go
@@ -31,7 +31,7 @@ func TestRing(t *testing.T) {
 var registerGossip sync.Once
 
 func testSim(t *testing.T, connect topology) {
-       const count = 3
+       const count = 150
 
        // set the log level to Trace
        log.Root().SetHandler(log.LvlFilterHandler(
@@ -100,7 +100,7 @@ func testSim(t *testing.T, connect topology) {
        }()
 
        // stop
-       <-time.After(5 * time.Second)
+       <-time.After(3600 * time.Second)
 
        if err := srv.Shutdown(context.TODO()); err != nil {
                log.Crit("Error stopping simulation server", "err", err)
```
3. run the test:
```
go test -timeout 20m -v ./integration/... 2>&1 | tee 00-integration.txt
```
4. After the test terminates in about 20 minutes, see the file `00-integration.txt` having no log record about any new block generated.

**Expected behavior**
20 minutes should be enough to reach consensus on 150 nodes. 
When consensus is reached, a new block is produced and the line similar to the following appears in the log:
```
INFO [11-18|20:54:39.561] New block                                index=1 hash=1:3:f72fffdd fee=0 txs=0 skipped_txs=0
```

**Comment by devintegral3** [comment]
It's not possible to run 150 validators on the same server, you'll not have enough resources for that (for technical reasons). In the most cases, it leads to connection deadlines and losing connections between peers.
Moreover, I wouldn't recommend to run more than 3 nodes in integration test (if test is long), or more than 10 nodes in docker demo.

**Comment by devintegral** [comment]
outdated
