### ISSUE TITLE
Proof-of-Stake

### ISSUE THREAD

**Issue by andrecronje** [Fantom-foundation/go-lachesis#39]
**Describe the solution you'd like**
- Reserve SmartContract as part of the Genesis block (it can be empty at this stage)
- Implement built-in emission
- Find link between EVM and transaction fees. Rewire this logic to channel transaction fees towards block rewards
- Distribute rewards to validators and reserve SmartContract. Keep it extensible because we will introduce weights later
- Further specify and document the PoS logic
- Write a set of SmartContracts to control the list of validators and their ‘bonded stakes’ (bonding, unbonding, slashing)
- Link between this SmartContract logic and consensus participant set
- Update Block rewards to distribute rewards proportionately to stake
- Add support for dynamic validator set

**Comment by devintegral** [comment]
outdated
