### ISSUE TITLE
Wrong delegation numbers (?)

### ISSUE THREAD

**Issue by rekt0x** [Fantom-foundation/go-lachesis#427]
## **What's the issue?**
It seems delegations that have already been undelegated are still counted towards the `delegatedMe`. I am developing https://fantomstaker.info and our staking metrics did not match up with those of the Explorer (http://explorer.fantom.network). Then I figured out that those values come from the Explorer API (https://api.fantom.network) which takes the values right out of the node (I guess). So I believe this is not just an API issue but an issue how the nodes store those values. By looking at the last epoch snapshot you can also see those values in total and for each validator and they also don't match up in my opinion.

## **Reproduce it**
Basically what I do is syncing all relevant EVM delegation events of the SFC Smart Contract, see here: https://github.com/block42-blockchain-company/fantom-staker-info/blob/master/backend/modules/Delegations.py

I end up with a database of all delegations that were ever made, including their status; if they are still active, they have been undelegated (= PreparedToWithdraw) or withdrawn (= WithdrawnDelegation).

When i now do some aggregation queries in mongodb and check e.g. Validator Nr. 1 (large validators are the best to showcase because there were also large amounts of delegations withdrawn), then i end up with a difference between my calculations and those showing in the explorer (api) as well as in the epoch snapshots of the SFC smart contract.

-----

Let's get all undelegated delegations of Validator Nr. 1, this ends up as: ~32,667,647 FTM

![image](https://user-images.githubusercontent.com/6087393/74102258-1b875480-4b42-11ea-834c-1c28baffa829.png)

Let's get all still active delegations to Validator Nr. 1, this ends up as: ~148,452,961 FTM

![image](https://user-images.githubusercontent.com/6087393/74102253-0d393880-4b42-11ea-81b2-5e18d341a0f0.png)

In https://fantomstaker.info we show the last number (~148M FTM), but when looking at the explorer api for Validator Nr. 1, see "delegatedMe" here: https://api.fantom.network/api/v1/staker/id/1
This value ends up being: ~181,638,535 FTM

Pretty much the same value (181,095,641 FTM) is also shown as the "delegatedMe" of Validator Nr. 1 in the latest epoch snapshot (Epoch 257).

![image](https://user-images.githubusercontent.com/6087393/74102193-7bc9c680-4b41-11ea-885e-2ed4455de04e.png)

-----

I believe it's no coincidence that when taking the numbers from my calculations, you also end up pretty much at the same number:  32,667,647 + 148,452,961 = 181,120,608 FTM

So I believe there is a severe issue in the calculation of the delegations which might (?) also affect the calculation of rewards.

-----

## **Expected behavior**
Undelegated delegations should be excluded from the "delegatedMe".

**Comment by MKong** [comment]
Thanks for noting the above. We are currently making the fix into the next release, timed for this week.
