### ISSUE TITLE
Deployment of smart contracts to Opera testnet fails with Truffle error "unknown account"

### ISSUE THREAD

**Issue by matprime** [Fantom-foundation/go-lachesis#442]
**Describe the bug**
Deployment of smart contracts to Opera testnet fails with Truffle. Smart contracts deployment/migration process to testnet doesn't recognize any account on testnet and fails with error. 

**To Reproduce**
1. Create smart contract within Truffle enabled repository
2. Compile it successfully with: "truffle compile"
3. Create migration script for smart contract
4. Define account which, should be used for deployment in migration script
5. Define host and port for Opera public testnet and from account in truffle-config.js
![Opera_testnet_configuration_in_truffle-config](https://user-images.githubusercontent.com/29488497/76433512-b75fe680-63b4-11ea-949e-2ae14573d526.jpg)
6. Deploy/migrate smart contract to Opera testnet with command: "truffle migrate"
7. See error
![smart_contracts_migration_fails](https://user-images.githubusercontent.com/29488497/76430429-9f866380-63b0-11ea-9d98-db75cd038503.jpg)

**Expected behavior**
Smart contract is deployed successfully to Opera testnet. Deployment is paid with testnet FTM from account defined in migration script.

**Desktop**
- OS: Linux Ubuntu 18.04
- Truffle v5.0.5
- Node v10.17.0 

**Additional context**
Link to repository used: https://github.com/matprime/meme-of-the-day-dApp

**Comment by elmaedesistemas** [comment]
exist a solution?

**Comment by ibrahim1023** [comment]
Hi, so we were able to deploy to the Opera-testnet without any issue using truffle configuration. If you can have a look at this repository (https://github.com/Fantom-foundation/example-deployment) and follow the steps given below, it should help you deploy a smart contract to Opera-testnet using truffle framework. Let us know if you still get any errors!
