### ISSUE TITLE
CheckSelfParent not matching results

### ISSUE THREAD

**Issue by andrecronje** [Fantom-foundation/go-lachesis#48]
**Describe the bug**
DEBU[0008] checkSelfParent                               

creator=0x0419E735BA4250C0C143E9276BDB1758BCD746730DFE0846DE4F2040D0F1A12B1E50B3527A198F3C8EBBF74E4EA94D3F42334B9FAC4C20F355D2ADEE9C59A5E114 
creatorLastKnown=0xFBA5CB84D56B5C57CBD9E24982137FC39156BE0E07CE3CDADAA343DC7958E730 
id=513203061 
selfParent=0xEDD51D57701CAFED90A31D6C79B4DD3B94334D57DAFFEBB10085278E1AE86D45

**Comment by Maxime2** [comment]
I take a look on this issue with help from @quan8

**Comment by quan8** [comment]
Put tracing around checkSelfParent(). 
Found out that the selfParent and creatorLastKnown are sometimes different on a single node.

a) when it goes wrong:
checkSelfParent()  selfParent= Root3868737032; creatorLastKnown= 0x063196ECE814446F4FE4CCC3DA52A3DE3A4EB0A8746552E635E0814A7C5FC68E

b) when it is ok, traces should look like this
checkSelfParent()  selfParent= 0xFD3EDFE2D7E24943E7E540F8492DA9BD6C198E0690D6E508CD77C47C6EFABF7B; creatorLastKnown= 0xFD3EDFE2D7E24943E7E540F8492DA9BD6C198E0690D6E508CD77C47C6EFABF7B

**Comment by quan8** [comment]
This error happened when syncing an event of node A to node B the second time.

**Comment by quan8** [comment]
The issue was fixed.
