### ISSUE TITLE
Versioning protocol

### ISSUE THREAD

**Issue by SamuelMarks** [Fantom-foundation/go-lachesis#53]
**Is your feature request related to a problem? Please describe.**
Since we're allowing nodes to join—#8 #10—it would be cognisant on us to confirm the version of each node joining the network.

**Describe the solution you'd like**
To start with, let's force everyone joining to have the same version.

**Describe alternatives you've considered**
Later, we can do something more in depth, like in the SSH standard: https://tools.ietf.org/html/rfc4253#section-4.2

**Additional context**
Will also be handy to start versioning the code base, we've been on 0.3.2 for too long!

**Comment by devintegral** [comment]
outdated
