### ISSUE TITLE
Some questions about the mainnet FTM

### ISSUE THREAD

**Issue by Wangmmx** [Fantom-foundation/go-lachesis#584]
Sorry I didn't find a suitable place to raise an issue. I just saw a recent update here, and I came here thinking that it would be more active.

1.I would like to ask whether the mainnet of FTM is now online? I used the testnet to get some test coins and completed the transfer function. Is the decimal of the mainnet FTM 18? I think the address of the FTM erc20 token is very similar to the address of the mainnet. How do I know that I am transferring the mainnet currency? This is a transaction I made on the testnet is https://explorer.testnet.fantom.network/transactions/0xb73a31173c386dd97bd16f4576df862da22672125f38f800b0f8f2b348423138, does it look correct? 

2.If the transaction is correct, what is the rpc external node of the main network? I also used the web wallet on the official website, but the wallet account cannot receive any FTM,  is it because the wallet is connected to the Mainnet and the browser uses the testnet? 

3.I have successfully transferred FTM on the testnet now, so how do I get the mainnet FTM?

Thanks a lot, looking forward to your reply!

**Comment by quan8** [comment]
@Wangmmx  can you please contact our support on Discord?
