### ISSUE TITLE
failed RPC connection to node1

### ISSUE THREAD

**Issue by ShallMate** [Fantom-foundation/go-lachesis#591]
failed RPC connection to node1,and I have tried to start start.sh many times

**Comment by quan8** [comment]
Hi @ShallMate , are you trying to set up a fakenet? Do you use release branch 0.7.0-rc1? You can go to Discord channel for support.

**Comment by ShallMate** [comment]
@quan8 Yes,i am I am  trying to set up a fakenet。And i an using the master branch, do I have to use 0.7.0-rc1?
