### ISSUE TITLE
Change all `int` that will be marshelled into int64 or int32

### ISSUE THREAD

**Issue by AgustinCB** [Fantom-foundation/go-lachesis#60]
**Describe the bug**
While working on #55, I noticed something problematic: A bunch of the structures that are being serialized to be later transmitted in the net are using type int. This is bad, since int is an alias for the architecture of the cpu. Not specifying it may cause problems if a node is running in a 32-bit machine while another one is running in a 64-bit machine. Furthermore, it adds complexity in the process of switching between different serialization methods, since of them (correctly) force you to specify integer size (like protobuf).

**Expected behavior**
All `int` types in structures that are going to be sent in the web should be changed to use `int64` or `int32` instead.

**Additional context**
I'm currently doing a first step on this as part of #55, but I'm trying to change the bare minimum to have that functionality working. My implementation will lay down the first steps, but we have to move further once that's merged.

**Comment by devintegral** [comment]
outdated
