### ISSUE TITLE
Syncing stuck at block 614958

### ISSUE THREAD

**Issue by sai-voiddev** [Fantom-foundation/go-lachesis#600]
My node syncing  is stuck at block 61958

**To Reproduce**
I followed the fantom.foundation docs to setup a full node.

**Screenshots**
![image](https://user-images.githubusercontent.com/11740157/113662157-d1e3bc80-96a7-11eb-9b4d-cad3843c8428.png)
![image](https://user-images.githubusercontent.com/11740157/113662186-de681500-96a7-11eb-986a-6b99329f6ab8.png)

 - ubuntu 20
 - aws ec2 : m5.2xlarge

**Comment by quan8** [comment]
@sai-voiddev which go-lachesis version are you using? 0.7.0-rc.1 ?

**Comment by sai-voiddev** [comment]
@quan8 its Version: 0.6.0-rc.3 i will try last release

Thank you

**Comment by sai-voiddev** [comment]
@quan8 so I updated to Version: 0.7.0-rc.1 but im still getting errors should I resync all from 0?

**Comment by quan8** [comment]
@sai-voiddev  Yeah, you may need to sync it from scratch.

Btw, we have a short guide to set up new readonly node. Please see the following link:
https://github.com/Fantom-foundation/lachesis_launch/blob/master/scripts/setup-validator-short.md#2-launch-a-read-only-lachesis-node
