### ISSUE TITLE
lachesis --your-favourite-flags dumpconfig can not work

### ISSUE THREAD

**Issue by linyintao2010** [Fantom-foundation/go-lachesis#604]
server :Ubuntu 16.04.6 LTS
[Opera.Emitter]
VersionToPublish = "1.0.0-rc.0"

running lachesis use --fakenet way 

and then execute below command ,can not get message than i expect.
lachesis dumpconfig config

how to obtain accurate execution configuration information for blockchain. where can get detail configuration info

**Comment by quan8** [comment]
Hi @linyintao2010 , did you see the the 'config' file generated?

**Comment by linyintao2010** [comment]
hi,i can get the  'config' file。But not the desired file，The information in it is inconsistent with the operation

**Comment by linyintao2010** [comment]
> Hi @linyintao2010 , did you see the the 'config' file generated?

hi,i can get the 'config' file。But not the desired file，The information in it is inconsistent with the operation. For example: the node information is wrong
