### ISSUE TITLE
can not find other validators 

### ISSUE THREAD

**Issue by linyintao2010** [Fantom-foundation/go-lachesis#605]
server :Ubuntu 16.04.6 LTS
[Opera.Emitter]
VersionToPublish = "1.0.0-rc.0"

After the node is running
Always show ：synchronizing (just joined the validators group）
![image](https://user-images.githubusercontent.com/30648802/116230956-d2451400-a78a-11eb-998f-ea0e1a9b498a.png)
How to solve this problem, thanks！

**Comment by quan8** [comment]
@linyintao2010  are you setting a fakenet? Can you please give some info, steps to reproduce?

**Comment by linyintao2010** [comment]
> @linyintao2010 are you setting a fakenet? Can you please give some info, steps to reproduce?

hello @quan8 Generate configuration file through --testnet。The genesis file was modified, the configuration file was generated, and 3 validators were obtained。

exec command：
./lachesis --legacy_config networklachesis.toml --config networkopera.toml --datadir=data --nousb

node some config info

![image](https://user-images.githubusercontent.com/30648802/116242311-5fdb3080-a798-11eb-9d74-bcaf4d65b010.png)


I tested telnet on port 7946 of each server, and it all worked.But just can’t find other verifiers

**Comment by linyintao2010** [comment]
> @linyintao2010 are you setting a fakenet? Can you please give some info, steps to reproduce?

At the same time, I use the ./lachesis attach method to enter  Lachesis JavaScript console!
Add a node through web3.admin.addPeer, which shows that the execution is successful. But the total number of nodes is still zero

**Comment by quan8** [comment]
@linyintao2010  Just wondering what you're trying to do "The genesis file was modified, the configuration file was generated ...".
It sounds like not in proper use.

**Comment by linyintao2010** [comment]
> @linyintao2010 Just wondering what you're trying to do "The genesis file was modified, the configuration file was generated ...".
> It sounds like not in proper use.

Couldn't it be possible to generate a configuration file through this？
