### ISSUE TITLE
How can I increase the number of block packaging transactions?

### ISSUE THREAD

**Issue by Ten-Ou** [Fantom-foundation/go-lachesis#606]
server :Ubuntu 18.04 LTS
[Opera.Emitter]
VersionToPublish = "1.0.0-rc.0"

I tried to use 110 address cycles to send 600 transactions to the go-lachesis chain within 2 seconds, but the speed of packing blocks on the chain is not fast, and the maximum number of block packing transactions is only a few dozen. For 600 transactions, it will take 5-6 seconds to complete the processing. I can't test the effect of hundreds or even thousands of tps.

**Comment by quan8** [comment]
@Ten-Ou If you are interested, please do it our testnet or set up a private testnet to try.
