### ISSUE TITLE
Lost Fonda

### ISSUE THREAD

**Issue by Iktaha** [Fantom-foundation/go-lachesis#623]
**Describe the bug**

Hi, I was transferring funds #fantom from Trust Wallet to Binance like I did the previous 2 times, but this time around, the transaction was stuck on pending and nothing was showing up on block chain explorer either so I reimported my wallet like the guide on the Trust Wallet forum. After reimporting, my pending transaction disappeared and the amount of funds I was transferring have vanished as well. They’ve been deducted from my Trust Wallet without the transaction actually going through. What should I do now to get lost crypto back

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by artimath** [comment]
Can you verify which network you sent the FTM to?
