### ISSUE TITLE
Node out of sync

### ISSUE THREAD

**Issue by COLUD4** [Fantom-foundation/go-lachesis#625]
Since last night, the node has stopped synchronizing data
![截屏2022-01-06 下午4 26 33](https://user-images.githubusercontent.com/21240219/148353213-d26a9e03-ef8f-467c-b0e2-dcacb56b08da.png)

**Comment by artimath** [comment]
Is it still not syncing for you? Why are you not using go-opera?

**Comment by quan8** [comment]
go-lachesis is not supported. Please use go-opera.
