### ISSUE TITLE
no Anchor Block in log

### ISSUE THREAD

**Issue by quan8** [Fantom-foundation/go-lachesis#81]
**Describe the bug**
Run 5 nodes. Got the following errors multiple times.

/home/qn/work/src/github.com/andrecronje/lachesis/cmd/lachesis/commands/run_lachesis_multi.go:49 +0x4a7
time="2018-11-12T21:03:59+11:00" level=error msg="n.requestFastForward(peer.NetAddr)" Error="no Anchor Block" this_id=3111831001

/home/qn/work/src/github.com/andrecronje/lachesis/src/node/state.go:51 +0x66
time="2018-11-12T21:03:59+11:00" level=error msg="n.core.GetAnchorBlockWithFrame()" error="no Anchor Block" this_id=945441204

**To Reproduce**
Run tests with 5 nodes

** OS **
Ubuntu 1, 64 bit

**Comment by SamuelMarks** [comment]
Trying to replicate. What's the exact command you're running?

I remember seeing this same error at some point…

**Comment by quan8** [comment]
It does not occur with the latest build.
