### ISSUE TITLE
events take long time for consensus on large number of nodes

### ISSUE THREAD

**Issue by quan8** [Fantom-foundation/go-lachesis#93]
When running on 15+ nodes, events take long time for consensus.
But it seems ok with <10 nodes.

**Comment by Maxime2** [comment]
The code speed is not related to this issue, as PR #114 doesn't solve this issue.

To clarify the title of the issue: currently Lachesis can not come to consensus on 15+ nodes, at all.
The problem lays perhaps either in new version of  strictlyDominated2(), which previously called stronglySee2(), either in the core of Lachesis itself, meaning something missed in the research paper.

Hint: for 15 nodes, roundInfo.SetAtropos(x, v) is never called in DecideAtropos() (in src/poset/poet.go)

**Comment by devintegral** [comment]
outdated
